### ISSUE TITLE
I can face a some issues while deploying my react app in gh-pages

### ISSUE THREAD

**Issue by fullstackfaizan** [fullstackfaizan/newmmrrrrr#1]
Run actions/deploy-pages@v2
Artifact exchange URL: https://pipelinesghubeus7.actions.githubusercontent.com/sOGbUXxXlz[9](https://github.com/fullstackfaizan/newmmrrrrr/actions/runs/6276066261/job/17044947636#step:2:10)OpEVO6wqadEJtWxlID3hOOaewafVZnOoGoomtih/_apis/pipelines/workflows/6276066261/artifacts?api-version=6.0-preview
Creating Pages deployment with payload:
{
	"artifact_url": "https://pipelinesghubeus7.actions.githubusercontent.com/sOGbUXxXlz9OpEVO6wqadEJtWxlID3hOOaewafVZnOoGoomtih/_apis/pipelines/1/runs/1/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "1f5aac4a2c9520933073141b[11](https://github.com/fullstackfaizan/newmmrrrrr/actions/runs/6276066261/job/17044947636#step:2:12)9164e4042aeb14",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: Invalid artifact url
    at /home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/api-client.js:[12](https://github.com/fullstackfaizan/newmmrrrrr/actions/runs/6276066261/job/17044947636#step:2:13)6:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/deployment.js:80:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 400) with build version 1f5aac4a2c9520933073[14](https://github.com/fullstackfaizan/newmmrrrrr/actions/runs/6276066261/job/17044947636#step:2:15)1b119[16](https://github.com/fullstackfaizan/newmmrrrrr/actions/runs/6276066261/job/17044947636#step:2:17)4e4042aeb14. Responded with: Invalid artifact url

**Comment by fullstackfaizan** [comment]
I don't know why this error occurs, if my site is publish then it show blank page even if i can not use any react router
